name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_SSH_HOST }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Verify deployment directory exists
            if [ ! -d "${{ secrets.DEPLOYMENT_PATH }}" ]; then
              echo "Creating deployment directory..."
              sudo mkdir -p ${{ secrets.DEPLOYMENT_PATH}}
              sudo chown -R $USER:$USER ${{ secrets.DEPLOYMENT_PATH}}
            fi

            cd ${{ secrets.DEPLOYMENT_PATH }}
            
            # Clone repo if not exists
            if [ ! -d ".git" ]; then
              git clone https://github.com/your-username/your-repo.git .
            fi

            # Update code
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Docker commands without sudo
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d --build

            